// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZo9hdASiCYYuVRNwnrm_Tsl-CMTXrNAk',
    appId: '1:389409259766:web:dd73da5706aa99d0a32cd7',
    messagingSenderId: '389409259766',
    projectId: 'emailapp-35b26',
    authDomain: 'emailapp-35b26.firebaseapp.com',
    storageBucket: 'emailapp-35b26.firebasestorage.app',
    measurementId: 'G-FPV0J1FKZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSly8JJYL7nrQXFZq6BhRgcdlgQni9h5s',
    appId: '1:389409259766:android:90bbf394177ef30ba32cd7',
    messagingSenderId: '389409259766',
    projectId: 'emailapp-35b26',
    storageBucket: 'emailapp-35b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8psengHhbkVMF0L_CGYdQmse_J2Tzo_A',
    appId: '1:389409259766:ios:f3958e658d6af4dba32cd7',
    messagingSenderId: '389409259766',
    projectId: 'emailapp-35b26',
    storageBucket: 'emailapp-35b26.firebasestorage.app',
    iosClientId: '389409259766-48m73r6d1je6tlcu6eseuesjflja2m3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.testabc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8psengHhbkVMF0L_CGYdQmse_J2Tzo_A',
    appId: '1:389409259766:ios:f3958e658d6af4dba32cd7',
    messagingSenderId: '389409259766',
    projectId: 'emailapp-35b26',
    storageBucket: 'emailapp-35b26.firebasestorage.app',
    iosClientId: '389409259766-48m73r6d1je6tlcu6eseuesjflja2m3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.testabc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZo9hdASiCYYuVRNwnrm_Tsl-CMTXrNAk',
    appId: '1:389409259766:web:6fbaadb909bfe05ea32cd7',
    messagingSenderId: '389409259766',
    projectId: 'emailapp-35b26',
    authDomain: 'emailapp-35b26.firebaseapp.com',
    storageBucket: 'emailapp-35b26.firebasestorage.app',
    measurementId: 'G-GJW6G5FQVR',
  );
}
